name: application_patient
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



   
   
  formwidget:
    path: package/formwidget
  cupertino_icons: ^1.0.2
   

  get: ^4.6.5
  lottie: ^1.3.0
  flutter_svg: ^1.1.0
  clay_containers: ^0.3.2
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.4
  shimmer: ^2.0.0
  fl_chart: ^0.55.0
  waveprogressbar_flutter: ^0.1.2
  intl: ^0.17.0
  chewie: ^1.3.4
  video_player:
  awesome_notifications:
  audioplayers: ^1.0.1
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  path: ^1.8.1
  shared_preferences: ^2.0.15
  circular_countdown_timer: ^0.2.2
  cached_network_image: ^3.2.2
  google_fonts: ^3.0.1
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.6
     
   
   






dev_dependencies:


  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.3+1

flutter_icons:
  android: "launcher_icon"
  color: "#FCFCFC"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/OnePeaceMed.png"

flutter_native_splash:
  color: "#FCFCFC"
  image: assets/logo/OnePeaceMed.png
  android_gravity: center
  ios: true



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/animations/
     - assets/icons/
     - assets/logo/
     - assets/categorie/
     - assets/video/
     - assets/water/
     - assets/water_assets/
   #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
